all: forkchildren5 forkchildren2

forkchildren5: forkchildren5.c
	gcc -Wall -g -std=c99 -Werror forkchildren5.c -o forkchildren5

forkchildren2: forkchildren2.c
	gcc -Wall -g -std=c99 -Werror forkchildren2.c -o forkchildren2

clean:
	rm forkchildren5 forkchildren2
